# Generated by Django 5.2.3 on 2025-08-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_tag_unique_lower_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='MainApp.tag'),
        ),
    ]
