# Generated by Django 5.2.3 on 2025-08-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.snippet'),
        ),
    ]
